In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

arr=np.array(my_list)
arr

array([1, 2, 3])

In [3]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(2)

array([1., 1.])

In [12]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.04921504, 0.24662151, 0.11586017, 0.29480455, 0.54622284])

In [15]:
np.random.rand(3,4)

array([[0.88888386, 0.97747584, 0.13246431, 0.50865058],
       [0.18059995, 0.00512261, 0.93311441, 0.23157823],
       [0.18993606, 0.75137572, 0.31029765, 0.82613407]])

In [16]:
np.random.randn(2)

array([0.33737083, 2.51415605])

In [17]:
np.random.randn(2,2)

array([[-0.08526186,  0.41376917],
       [-0.35690937, -0.16082456]])

In [20]:
np.random.randint(1,100,10)

array([95,  7, 31, 90, 88, 88, 29, 37, 27, 18], dtype=int32)

In [21]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr=np.random.randint(0,50,10)

In [23]:
ranarr

array([14, 46, 31, 34, 42, 36, 30,  6, 36, 43], dtype=int32)

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr.max()

np.int64(24)

In [26]:
arr.min()

np.int64(0)

In [27]:
ranarr.min()

np.int32(6)

In [28]:
arr.argmax()

np.int64(24)

In [30]:
ranarr.argmin()

np.int64(7)

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr.shape

(25,)

In [35]:
arr.dtype

dtype('int64')

In [36]:
from numpy.random import randint

In [37]:
randint(2,5)

3

In [38]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [39]:
arr=np.arange(0,10)

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[1:5]

array([1, 2, 3, 4])

In [45]:
arr[5:]

array([5, 6, 7, 8, 9])

In [46]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [47]:
arr=np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
slice_of_arr=arr[0:6]

In [51]:
slice_of_arr[:]=99

In [52]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [54]:
arr_copy=arr.copy()

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr_copy[:]=100

In [58]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [59]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
import numpy as np

In [62]:
arr_2d=np.array([[5,10,5],[15,20,25],[35,40,45]])

In [63]:
arr_2d

array([[ 5, 10,  5],
       [15, 20, 25],
       [35, 40, 45]])

In [66]:
arr_2d[1][2]

np.int64(25)

In [67]:
arr_2d[1,2]

np.int64(25)

In [69]:
arr_2d[:2,1:]

array([[10,  5],
       [20, 25]])

In [70]:
arr_2d[:2]

array([[ 5, 10,  5],
       [15, 20, 25]])

In [71]:
arr=np.arange(1,11)

In [72]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [74]:
bool_Arr=arr>5

In [76]:
arr[bool_Arr]

array([ 6,  7,  8,  9, 10])

In [77]:
arr_3d=np.arange(50).reshape(5,10)

In [78]:
arr_3d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [79]:
arr_3d[2:3,4:6]

array([[24, 25]])